import { StyleSheet } from "@react-pdf/renderer";

/** Light print-friendly tokens aligned with Solr Playground globals.css */
export const reportColors = {
  accent: "#4a9e7a",
  accentMuted: "#3d7a62",
  accentTint: "#4a9e7a18",
  text: "#1a1a1a",
  textMuted: "#6b7280",
  border: "#e5e7eb",
  cardBg: "#fafafa",
  pageBg: "#ffffff",
  neutralTint: "#f3f4f6",
  tieBorder: "#d1d5db",
} as const;

export const reportFonts = {
  sans: "Inter",
  sansBold: "Inter-SemiBold",
  mono: "Courier",
} as const;

export const reportSpacing = {
  pagePaddingTop: 52,
  pagePaddingBottom: 56,
  pagePaddingHorizontal: 48,
  cardRadius: 8,
  sectionGap: 14,
  accentBarHeight: 4,
} as const;

export const reportStyles = StyleSheet.create({
  page: {
    paddingTop: reportSpacing.pagePaddingTop,
    paddingBottom: reportSpacing.pagePaddingBottom,
    paddingHorizontal: reportSpacing.pagePaddingHorizontal,
    fontSize: 10,
    fontFamily: reportFonts.sans,
    color: reportColors.text,
    backgroundColor: reportColors.pageBg,
  },
  accentBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: reportSpacing.accentBarHeight,
    backgroundColor: reportColors.accent,
  },
  pageHeader: {
    marginBottom: 16,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: reportColors.border,
  },
  pageHeaderTitle: {
    fontSize: 15,
    fontFamily: reportFonts.sansBold,
    color: reportColors.text,
  },
  pageHeaderProduct: {
    fontSize: 8,
    color: reportColors.accentMuted,
    marginBottom: 2,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  coverTitle: {
    fontSize: 26,
    fontFamily: reportFonts.sansBold,
    color: reportColors.text,
    marginTop: 48,
    marginBottom: 6,
  },
  coverSubtitle: {
    fontSize: 13,
    color: reportColors.textMuted,
    marginBottom: 28,
  },
  coverContext: {
    fontSize: 10,
    lineHeight: 1.55,
    color: reportColors.textMuted,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 13,
    fontFamily: reportFonts.sansBold,
    marginBottom: 10,
    color: reportColors.text,
  },
  subsection: {
    fontSize: 10,
    fontFamily: reportFonts.sansBold,
    marginTop: 12,
    marginBottom: 6,
    color: reportColors.text,
  },
  body: {
    fontSize: 10,
    lineHeight: 1.5,
    marginBottom: 6,
    color: reportColors.text,
  },
  bodyMuted: {
    fontSize: 9,
    lineHeight: 1.45,
    color: reportColors.textMuted,
  },
  mono: {
    fontFamily: reportFonts.mono,
    fontSize: 8.5,
    lineHeight: 1.4,
    color: reportColors.text,
  },
  bullet: {
    fontSize: 9,
    lineHeight: 1.45,
    marginBottom: 4,
    paddingLeft: 10,
    color: reportColors.textMuted,
  },
  footer: {
    position: "absolute",
    bottom: 22,
    left: reportSpacing.pagePaddingHorizontal,
    right: reportSpacing.pagePaddingHorizontal,
    fontSize: 7.5,
    color: reportColors.textMuted,
    textAlign: "center",
    borderTopWidth: 0.5,
    borderTopColor: reportColors.border,
    paddingTop: 8,
  },
  card: {
    borderWidth: 1,
    borderColor: reportColors.border,
    borderRadius: reportSpacing.cardRadius,
    backgroundColor: reportColors.cardBg,
    padding: 12,
    marginBottom: 10,
  },
  cardAccentStripe: {
    position: "absolute",
    left: 0,
    top: 8,
    bottom: 8,
    width: 3,
    backgroundColor: reportColors.accent,
    borderRadius: 2,
  },
  callout: {
    borderWidth: 1,
    borderColor: reportColors.border,
    borderRadius: reportSpacing.cardRadius,
    backgroundColor: reportColors.neutralTint,
    padding: 12,
    marginBottom: 10,
  },
  kpiGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 16,
  },
  kpiCard: {
    width: "47%",
    borderWidth: 1,
    borderColor: reportColors.border,
    borderRadius: reportSpacing.cardRadius,
    backgroundColor: reportColors.cardBg,
    padding: 10,
  },
  kpiLabel: {
    fontSize: 7.5,
    color: reportColors.textMuted,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 4,
  },
  kpiValue: {
    fontSize: 11,
    fontFamily: reportFonts.sansBold,
    color: reportColors.text,
  },
  monoBox: {
    borderWidth: 1,
    borderColor: reportColors.border,
    borderRadius: 6,
    backgroundColor: reportColors.pageBg,
    padding: 8,
    marginTop: 8,
  },
  tableWrap: {
    borderWidth: 1,
    borderColor: reportColors.border,
    borderRadius: reportSpacing.cardRadius,
    overflow: "hidden",
    marginBottom: 14,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: reportColors.neutralTint,
    borderBottomWidth: 1,
    borderBottomColor: reportColors.border,
    paddingVertical: 6,
    paddingHorizontal: 8,
    fontFamily: reportFonts.sansBold,
    fontSize: 8.5,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: reportColors.border,
    paddingVertical: 5,
    paddingHorizontal: 8,
    fontSize: 8.5,
  },
  tableRowHighlight: {
    backgroundColor: reportColors.accentTint,
  },
  colMetric: { width: "28%" },
  colA: { width: "36%" },
  colB: { width: "36%" },
  chipGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  chip: {
    width: "31%",
    borderWidth: 1,
    borderColor: reportColors.border,
    borderRadius: 6,
    backgroundColor: reportColors.cardBg,
    padding: 8,
  },
  chipLabel: {
    fontSize: 7,
    color: reportColors.textMuted,
    marginBottom: 3,
  },
  chipValue: {
    fontSize: 10,
    fontFamily: reportFonts.sansBold,
    color: reportColors.text,
  },
  verdictCard: {
    borderWidth: 1.5,
    borderColor: reportColors.accent,
    borderRadius: reportSpacing.cardRadius,
    backgroundColor: reportColors.accentTint,
    padding: 14,
    marginBottom: 12,
  },
  verdictCardTie: {
    borderColor: reportColors.tieBorder,
    backgroundColor: reportColors.neutralTint,
  },
  verdictTitle: {
    fontSize: 14,
    fontFamily: reportFonts.sansBold,
    color: reportColors.accentMuted,
    marginBottom: 4,
  },
  verdictTitleTie: {
    color: reportColors.textMuted,
  },
  confidencePill: {
    alignSelf: "flex-start",
    fontSize: 8,
    color: reportColors.accentMuted,
    borderWidth: 1,
    borderColor: reportColors.accent,
    borderRadius: 4,
    paddingVertical: 2,
    paddingHorizontal: 6,
    marginBottom: 8,
  },
  appendixItem: {
    borderWidth: 1,
    borderColor: reportColors.border,
    borderRadius: 6,
    backgroundColor: reportColors.cardBg,
    padding: 8,
    marginBottom: 6,
    flexDirection: "row",
    gap: 8,
  },
  rankBadge: {
    fontSize: 9,
    fontFamily: reportFonts.sansBold,
    color: reportColors.accentMuted,
    minWidth: 24,
  },
});
